console.log("Hello selva");
var a = 10;
console.log("The value of a is ".concat(a));
var str = "Welcome to typescript";
console.log("".concat(str));
var s;
s = "hiii vjselva";
console.log("".concat(s));
var strAny;
strAny = 10;
console.log("The value of strAny ".concat(strAny));
strAny = 2.5;
console.log("The value of strAny ".concat(strAny));
strAny = true;
console.log("The value of strAny ".concat(strAny));
var c;
c = 10;
console.log("The value of c ".concat(c));
c = false;
console.log("The value of c ".concat(c));
var d;
d = null;
console.log("The value of d ".concat(d));
d = true;
console.log("The value of d ".concat(d));
